website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.orm import relationship
from sqlalchemy.schema import Column, ForeignKey
from sqlalchemy.types import INTEGER, String, DATETIME, BOOLEAN
from sqlalchemy.sql import func


class Note(db.Model):
    id = Column(INTEGER, primary_key=True)
    data = Column(String(10000))
    date = Column(DATETIME(timezone=True), default=func.now())
    user_id = Column(INTEGER, ForeignKey("user.id"))


class Disaster(db.Model):
    id = Column(INTEGER, primary_key=True)
    title = Column(String(512))
    desc = Column(String(5000))
    location = Column(String(512))
    is_resolved = Column(BOOLEAN, default=False)
    user_id = Column(INTEGER, ForeignKey("user.id"))


class User(db.Model, UserMixin):
    id = Column(INTEGER, primary_key=True)
    email = Column(String(150), unique=True)
    password = Column(String(150))
    name = Column(String(150))
    notes = relationship("Note")

website/__init__.py
from os import path
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager


db = SQLAlchemy()
DB_NAME = "model.db"


def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = "asdfkjkhdkahdkhfhadfkah"
    # app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = True
    # app.config["SQLALCHEMY_ECHO"] = True
    app.config["SQLALCHEMY_DATABASE_URI"] = f"""sqlite:///{DB_NAME}"""
    db.init_app(app)

    from .html_test import html_test
    from .auth import auth
    from .views import views

    app.register_blueprint(html_test, url_prefix="/test")
    app.register_blueprint(auth, url_prefix="/")
    app.register_blueprint(views, url_prefix="/")

    from .models import User, Note

    create_database(app)

    login_manager = LoginManager(app=app)
    login_manager.login_view = "auth.login"

    @login_manager.user_loader
    def load_user(id):
        return db.session.query(User).get(int(id))

    return app


def create_database(app):
    if not path.exists("website/" + DB_NAME):
        db.create_all(app=app)
        print("Created Database!")

website/auth.py
from flask import Blueprint, render_template, request, flash, url_for, redirect
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import check_password_hash, generate_password_hash
from .models import User
from . import db

auth = Blueprint("auth", __name__)


@auth.route("/sign-up", methods=["POST", "GET"])
def sign_up():
    if request.method == "POST":
        email = request.form.get("email")
        name = request.form.get("name")
        pwd = request.form.get("pass")
        pass_conf = request.form.get("pass_conf")

        user = User.query.filter_by(email=email).first()

        if user:
            flash("Email already exists.", category="error")
        elif len(email) < 4:
            flash("Email must be greater than 3 characters.", category="error")
        elif len(name) < 2:
            flash("First name must be greater than 1 character.", category="error")
        elif pwd != pass_conf:
            flash("Passwords don't match.", category="error")
        elif len(pwd) < 7:
            flash("Password must be at least 7 characters.", category="error")
        else:
            new_user = User(
                email=email,
                name=name,
                password=generate_password_hash(pwd, method="sha256"),
            )
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash("Account created!", category="success")
            return redirect(url_for("views.home"))

    return render_template("sign-up.html", user=current_user, nav=False)


@auth.route("/login", methods=["POST", "GET"])
def login():
    if request.method == "POST":
        user = db.session.query(User).filter_by(email=request.form.get("email")).first()

        if user:
            if check_password_hash(user.password, request.form.get("pass")):
                login_user(user, remember=True)
                flash(
                    f"Logged in as {current_user.name.capitalize()}!",
                    category="success",
                )
                return redirect(url_for("views.home"))
            else:
                flash("Incorrect Password!", category="error")
        else:
            flash("Incorrect Email!", category="error")

    return render_template("login.html", user=current_user, nav=False)


@auth.route("/logout")
@login_required
def logout():
    flash(
        f"{current_user.name.capitalize()} Logged out successfully!", category="success"
    )
    logout_user()
    return redirect(url_for("auth.login"))

website/views.py
from flask import Blueprint, render_template, request, flash
from flask_login import login_required, current_user
import json
from .models import Disaster
from . import db


views = Blueprint("views", __name__)


@views.route("/")
@login_required
def home():
    disaster_query = Disaster.query.all()
    disasters = [
        {
            "id": disaster.id,
            "title": disaster.title,
            "description": disaster.desc,
            "location": disaster.location,
            "is_resolved": disaster.is_resolved,
            "user_id": disaster.user_id,
        }
        for disaster in disaster_query
    ]
    print(disasters)
    return render_template("home.html", user=current_user, disasters=disasters)


@views.route("/add", methods=["GET", "POST"])
@login_required
def add_disaster():
    if request.method == "POST":
        title = request.form.get("title")
        description = request.form.get("description")
        location = request.form.get("location")

        disaster = Disaster(
            title=title,
            desc=description,
            location=location,
            user_id=current_user.id,
        )
        db.session.add(disaster)
        db.session.commit()

        flash(f"Successfully Added Entry", "success")
        return render_template("add_disaster.html", user=current_user)

    return render_template("add_disaster.html", user=current_user)

website/templates/add_disaster.html
{% extends 'base.html' %}

{% block title %}Add Disaster{% endblock %}

{% block content %}
<section class="vh-100" style="background-color: #91c7fc;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-xl-10">
          <div class="card" style="border-radius: 1rem;">
            <div class="row g-0">
              <div class="d-flex align-items-center">
                <div class="card-body p-4 p-lg-5 text-black">
  
                  <form method="post" class="container">

                    <div class="d-flex align-items-center mb-3 pb-1">
                     
                      <span class="h1 fw-bold mb-0" style="color: #302b2b;">Add Details</span>
                    </div>
  
  
                    <div class="form-outline mb-4">
                      <input type="text" id="title" required name="title" class="form-control form-control-lg" />
                      <label class="form-label" for="title">Title</label>
                    </div>

                    
                    <div class="form-outline mb-4">
                        <textarea type="text" id="description" required name="description" class="form-control form-control-lg"></textarea>
                        <label class="form-label" for="description">Description</label>
                    </div>

                    <div class="form-outline mb-4">
                        <input type="text" id="location" required name="location" class="form-control form-control-lg" />
                        <label class="form-label" for="location">Location</label>
                      </div>

                    <div class="pt-1 mb-4">
                      <button style="background-color: #3b71ca; color: azure;" class="btn btn-lg btn-block" type="submit">Add</button>
                    </div>

                  </form>
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}


website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0" />
    <title>
      {% block title %}
        base
      {% endblock %}
    </title>
    <meta name="description"  content="Green Thumbs"/>
    <!-- Latest compiled and minified CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    
    <!-- Google Fonts -->
    <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    rel="stylesheet"
    />
    <!-- MDB -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.0/mdb.min.css"
    rel="stylesheet"
    />
    <link rel="stylesheet" 
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" 
    integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" 
    crossorigin="anonymous" referrerpolicy="no-referrer" />


    
    <link href="{{url_for('static', filename='vendor/aos/aos.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='vendor/boxicons/css/boxicons.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='vendor/glightbox/css/glightbox.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='vendor/swiper/swiper-bundle.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='style.css')}}" rel="stylesheet">


    <!-- Google Fonts -->

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">
  </head>

  <body>
    {% set nav = nav if nav==false else true %}
    {% if nav %}
    
    
    <nav class="navbar navbar-expand" style="font-family:'Open Sans'; padding: 0.5em 0em;">
      <h1 style="padding-left:2rem; color: rgb(81, 82, 82); font-weight: 700;" ><span>NDRF</span></h1>
     
      <div class="collapse navbar-collapse" id="navbar" style="margin-left: auto; width: fit-content; display:flex;justify-content:flex-end; padding-right:4rem;">
        <div class="navbar-nav" style="gap:3rem;">
          {% if user.is_authenticated %}
              <a class="nav-item nav-link scrollto" id="home" href="/">Home</a>
              <a class="nav-item nav-link scrollto" id="add_disaster" href="/add">Add Disaster</a>
              <a class="nav-item nav-link scrollto" id="logout" href="/logout">Logout</a>
          {% else %}
              <a class="nav-item nav-link scrollto" id="login" href="/login">Login</a>
              <a class="nav-item nav-link scrollto" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
          
        </div>
      </div>
    </nav>
    {% endif %}

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for category, message in messages %}
              {% if category == 'error' %}
                <div class="alert alert-danger alert-dismissable fade show text-center" style="position: absolute; left: 0px; right: 0px;" role="alert">
                    {{message}}
                    <button type="button" class="close" data-dismiss="alert">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                </div>
              {% else %}
                <div class="alert alert-success alert-dismissable fade show text-center" style="position: absolute;left: 0px; right: 0px" role="alert">
                  {{message}}
                  <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endif %}
          {% endfor %}
      {% endif %}
    {% endwith %}
    
    {% block content %}

    {% endblock %}

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  
    <script type="text/javascript" src="{{url_for('static', filename='index.js')}}"></script>
  
    <!-- MDB -->
    <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.0/mdb.min.js"
    ></script>
    
    <script type="text/javascript" src="{{url_for('static', filename='vendor/aos/aos.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='vendor/glightbox/js/glightbox.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='vendor/isotope-layout/isotope.pkgd.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='vendor/swiper/swiper-bundle.min.js')}}"></script>

    <script  src="{{url_for('static', filename='main.js')}}"></script>
    <script  src="{{url_for('static', filename='housePlants.js')}}"></script>
    

  </body>
</html>

website/templates/home.html
{% extends 'base.html' %}


{% block title %}Home{% endblock %}


{% block content %}
<style>
  .location-icon{
    color: #ff628e!important;
    display: flex !important;
    align-items: center;
    justify-items: center;
    gap: .5rem !important;
    margin-top: 8px !important;
  }
</style>


<section id="hero" class="d-flex align-items-center">

  <div class="container d-flex flex-column align-items-center justify-content-center" style="padding-top:0px ;" data-aos="fade-up">
    <h1>National Disaster Response Force Community</h1>
    <h2>Empowering Collaboration for Effective Disaster Relief</h2>
    <a href="{{url_for('views.add_disaster')}}" class="btn-get-started scrollto">Update Disaster</a>
    <img src="static/Images/hero-img.png" class="img-fluid hero-img" alt="" data-aos="zoom-in" data-aos-delay="150">
  </div>

</section>


<!-- Features -->

<section id="features" class="features" data-aos="fade-up">
  <div class="container">

    <div class="section-title">
      <h2>Features</h2>
      
    </div>

    <div class="row content">
      <div class="col-md-5" data-aos="fade-right" data-aos-delay="100">
        <img src="static/Images/features-1.png" class="img-fluid" alt="">
      </div>
      <div class="col-md-7 pt-4" data-aos="fade-left" data-aos-delay="100">
        <h3>Real-time Updates</h3>
        <p class="fst-italic">
        Stay updated with the latest disaster alerts, situational reports, and response efforts initiated by the NDRF, NSS, and NCC. Timely information is crucial for effective response and assisting affected communities.
        </p>
      </div>
    </div>

    <div class="row content">
      <div class="col-md-5 order-1 order-md-2" data-aos="fade-left">
        <img src="static/Images/features-2.png" class="img-fluid" alt="">
      </div>
      <div class="col-md-7 pt-5 order-2 order-md-1" data-aos="fade-right">
        <h3>Collaboration Hub</h3>
        <p class="fst-italic">Connect with dedicated individuals and organizations involved in disaster response across the nation. Share insights, resources, and best practices to enhance the collective capacity to handle emergencies effectively.          
        </p>
      </div>
    </div>

    <div class="row content">
      <div class="col-md-5" data-aos="fade-right">
        <img src="static/Images/features-3.png" class="img-fluid" alt="">
      </div>
      <div class="col-md-7 pt-5" data-aos="fade-left">
        <h3>Training and Knowledge Center</h3>
        <p>Access a comprehensive repository of training materials, guidelines, and case studies to enhance your skills and knowledge in disaster response and relief operations. Learn from experienced professionals and leverage this knowledge to save lives and mitigate the impact of disasters.
        </p>
      </div>
    </div>

    <div class="row content">
      <div class="col-md-5 order-1 order-md-2" data-aos="fade-left">
        <img src="static/Images/features-4.png" class="img-fluid" alt="">
      </div>
      <div class="col-md-7 pt-5 order-2 order-md-1" data-aos="fade-right">
        <h3>Volunteer Opportunities</h3>
        <p class="fst-italic">Discover volunteering opportunities with the NDRF, NSS, and NCC, and contribute your time, skills, and resources towards helping those in need. Join hands with like-minded individuals to make a difference in the lives of disaster-affected communities.
        </p>
      </div>
    </div>

  </div>
</section>

<!-- Features -->


    <!-- ======= Steps Section ======= -->
    <section id="steps" class="steps">
      <div class="container">

        <div class="section-title">
          <h2>Recent Updates</h2>
          
        </div>
        <div class="row no-gutters" data-aos="fade-up">

          {% for disaster in disasters %}
            {%   if disaster.is_resolved == false %}

              <div class="col-lg-4 col-md-6 px-4 p-md-4 content-item" data-aos="fade-up" data-aos-delay="100">
                <span>{{disaster.title}}</span>
                <p>{{disaster.description}}</p>
                <p class="location-icon"><i class="fa-sharp fa-solid fa-location-dot"></i>{{disaster.location}}</p>
              </div>

            {% endif %}

          {% endfor %}

        </div>

      </div>
    </section><!-- End Steps Section -->

    <!-- Links -->

    <section id="portfolio" class="portfolio">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Training and Knowledge Center</h2>
          <p>We strive to create a unified and robust network of volunteers, professionals, and organizations committed to alleviating the suffering caused by calamities. Through this platform, you can stay informed about ongoing disaster situations, connect with fellow responders, and leverage the collective expertise and resources to ensure swift and efficient relief efforts.</p>
        </div>


        <div class="row portfolio-container">


        <div class="col-lg-4 col-md-6 portfolio-item filter-app">
          <div class="portfolio-wrap">
            <img style="aspect-ratio:16/9; object-fit: cover;" src="https://nss.gov.in/sites/default/files/styles/nss_home_page_slider/public/PM%20House-min.jpg?itok=gXXjloGt" class="img-fluid" alt="">
            <div class="portfolio-info">
              <h4>NSS Indian Government</h4>
              <p>The Motto of NSS "Not Me But You", reflects the essence of democratic living and upholds the need for self-less service.</p>
              <div class="portfolio-links">
                
                <a href="https://nss.gov.in/" title="More Details"><i class="bx bx-link"></i></a>
              </div>
            </div>
          </div>
        </div>

        <div class="col-lg-4 col-md-6 portfolio-item filter-app" >
          <div class="portfolio-wrap">
            <img style="aspect-ratio:16/9; object-fit: cover;" src="https://www.rotary.org/sites/default/files/styles/w_1200/public/rm-may23-projects-nepal.jpg?itok=jmUCcgF2" class="img-fluid" alt="">
            <div class="portfolio-info">
              <h4>Rotary Club</h4>
              <p>Solving some of the world’s most complex and pressing problems takes real commitment and vision. Rotary members believe that we share a responsibility to take action to improve our communities.</p>
              <div class="portfolio-links">
                
                <a href="https://www.rotary.org/en" title="More Details"><i class="bx bx-link"></i></a>
              </div>
            </div>
          </div>
        </div>

        </div>

       </div>
       </section> 

       <!-- FAQS -->

       <section id="faq" class="faq">
        <div class="container" data-aos="fade-up">
  
          <div class="section-title">
            <h2>Frequently Asked Questions</h2>
          </div>
  
          <ul class="faq-list">
  
            <li>
              <div data-bs-toggle="collapse" class="collapsed question" href="#faq1">What is the National Disaster Response Force (NDRF)? <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
              <div id="faq1" class="collapse" data-bs-parent=".faq-list">
                <p>
                  The National Disaster Response Force (NDRF) is a specialized force in India that is dedicated to disaster response, rescue operations, and relief efforts during natural or man-made disasters.
                </p>
              </div>
            </li>
  
            <li>
              <div data-bs-toggle="collapse" href="#faq2" class="collapsed question">What is the role of the National Service Scheme (NSS) and National Cadet Corps (NCC) in disaster response? <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
              <div id="faq2" class="collapse" data-bs-parent=".faq-list">
                <p>
                  The National Service Scheme (NSS) and National Cadet Corps (NCC) are youth organizations in India that actively participate in disaster response activities. They assist in providing manpower, spreading awareness, and supporting relief operations during times of crisis.
              </div>
            </li>
  
            <li>
              <div data-bs-toggle="collapse" href="#faq3" class="collapsed question">How can I stay updated about ongoing disaster situations? <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
              <div id="faq3" class="collapse" data-bs-parent=".faq-list">
                <p>
                  The website provides real-time updates on disaster alerts, situational reports, and response efforts initiated by the NDRF, NSS, and NCC. Regularly visit the website.
                </p>
              </div>
            </li>
  
            <li>
              <div data-bs-toggle="collapse" href="#faq4" class="collapsed question">How can I contribute to disaster relief efforts through the website?<i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
              <div id="faq4" class="collapse" data-bs-parent=".faq-list">
                <p>
                  There are several ways to contribute. You can volunteer your time and skills by joining the NDRF, NSS, or NCC. Additionally, you can donate resources, participate in fundraising campaigns, or provide relevant information and expertise to support relief operations.
                </p>
              </div>
            </li>
  
            <li>
              <div data-bs-toggle="collapse" href="#faq5" class="collapsed question">How can I connect with other responders and organizations? <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
              <div id="faq5" class="collapse" data-bs-parent=".faq-list">
                <p>
                  The website provides a collaboration hub where you can connect with like-minded individuals, professionals, and organizations involved in disaster response. Engage in discussions, share insights, and explore collaborative opportunities to enhance collective response efforts.
                </p>
              </div>
            </li>
  
  
          </ul>
  
        </div>
      </section>

      <!-- End of FAQS -->

{% endblock %}

website/templates/login.html
{% extends 'base.html' %}

{% block title %}SignUp{% endblock %}

{% block content %}
<section class="vh-100" style="background-color: #91c7fc;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-xl-10">
          <div class="card" style="border-radius: 1rem;">
            <div class="row g-0">
              <div class="col-md-6 col-lg-5 d-none d-md-block">
                <img src="https://images.pexels.com/photos/13290381/pexels-photo-13290381.jpeg?auto=compress&cs=tinysrgb&w=1600"
                  alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem; height: 100%; object-fit: cover; object-position: left 0px; " />
              </div>
              <div class="col-md-6 col-lg-7 d-flex align-items-center">
                <div class="card-body p-4 p-lg-5 text-black">
  
                  <form method="post" class="container">
  
                    <div class="d-flex align-items-center mb-3 pb-1">
                     
                      <span class="h1 fw-bold mb-0" style="color: #302b2b;">NDRF</span>
                    </div>
  
                    <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Welcome Again!!!</h5>
  
                    <div class="form-outline mb-4">
                      <input type="email" id="email" required name="email" class="form-control form-control-lg" autocomplete="email" />
                      <label class="form-label" for="email">Email address</label>
                    </div>

                    <div class="form-outline mb-4">
                      <input type="password" id="pass" required name="pass" class="form-control form-control-lg" autocomplete="current-password" />
                      <label class="form-label" for="pass">Password</label>
                    </div>

                    <div class="pt-1 mb-4">
                      <button style="background-color: #3b71ca; color: azure;" class="btn btn-lg btn-block" type="submit">Login</button>
                    </div>
  
                    <p class="mb-5 pb-lg-2" style="color: #302b2b;">Don't have an account? <a href="{{url_for('auth.sign_up')}}"
                        style="color: #de556c; text-decoration: underline;">Register</a>
                    </p>
                  </form>
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

website/templates/sign-up.html
{% extends 'base.html' %}

{% block title %}SignUp{% endblock %}

{% block content %}
<section class="vh-100" style="background-color: #91c7fc;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-xl-10">
          <div class="card" style="border-radius: 1rem;">
            <div class="row g-0">
              <div class="col-md-6 col-lg-5 d-none d-md-block">
                <img src="https://images.pexels.com/photos/13290381/pexels-photo-13290381.jpeg?auto=compress&cs=tinysrgb&w=1600"
                  alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem; height: 100%; object-fit: cover;  object-position: left 0px; " />
              </div>
              <div class="col-md-6 col-lg-7 d-flex align-items-center">
                <div class="card-body p-4 p-lg-5 text-black">
  
                  <form method="post" class="container">
  
                    <div class="d-flex align-items-center mb-3 pb-1">
                      
                      <span class="h1 fw-bold mb-0" style="color: #302b2b;">NDRF</span>
                    </div>
  
                    <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">First step to get into Community</h5>
  
                    <div class="form-outline mb-4">
                      <input type="email" id="email" required name="email" class="form-control form-control-lg" />
                      <label class="form-label" for="email">Email address</label>
                    </div>

                    <div class="form-outline mb-4">
                        <input type="text" id="name" name="name" required  class="form-control form-control-lg" />
                        <label class="form-label" for="name">Name</label>
                      </div>
  
                    <div class="form-outline mb-4">
                      <input type="password" id="pass" required name="pass" class="form-control form-control-lg" />
                      <label class="form-label" for="pass">Password</label>
                    </div>

                    <div class="form-outline mb-4">
                        <input type="password" id="pass_conf"name="pass_conf" required  class="form-control form-control-lg" />
                        <label class="form-label" for="pass_conf">Confirm Password</label>
                      </div>
  
                    <div class="pt-1 mb-4">
                      <button style="background-color: #3b71ca; color: azure;" class="btn btn-lg btn-block" type="submit">Sign Up</button>
                    </div>
  
                    <p class="mb-5 pb-lg-2" style="color: #302b2b;">Already have an account? <a href="{{url_for('auth.login')}}"
                        style="color: #de556c; text-decoration: underline;">Login</a></p>
                    
                  </form>
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}